version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bullystop-network
    command: >
      bash -c "
        echo 'host all all 0.0.0.0/0 md5' >> /var/lib/postgresql/data/pg_hba.conf;
        echo 'host all all ::/0 md5' >> /var/lib/postgresql/data/pg_hba.conf;
        postgres -c listen_addresses='*'
      "

volumes:
  postgres_data:
    name: bullystop-postgres-data
    external: false

networks:
  bullystop-network:
    name: bullystop-network
    driver: bridge
