version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bullystop-db
    environment:
      POSTGRES_USER: bullystop
      POSTGRES_PASSWORD: bullystop123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bullystop"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bullystop-network

volumes:
  postgres_data:

networks:
  bullystop-network:
    driver: bridge 